### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by skshadan** [JoseHenriqueSiqueira/WhatsaAppChatBot_OpenaiChatGPT_Python#11]
```
DevTools listening on ws://127.0.0.1:59927/devtools/browser/0569e453-36dd-44d2-a025-0b1f63e5b263
[4932:28996:0807/155149.528:ERROR:device_event_log_impl.cc(222)] [15:51:49.527] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
[4932:28996:0807/155149.541:ERROR:device_event_log_impl.cc(222)] [15:51:49.540] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[4932:28996:0807/155149.558:ERROR:device_event_log_impl.cc(222)] [15:51:49.557] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "e:\KL2.0\CODEZ\Whatsapp_Instagram_Messanger_ChatGPT_OpenAI\InstagramBot.py", line 66, in <module>
    InstBOT.BotStart()
  File "e:\KL2.0\CODEZ\Whatsapp_Instagram_Messanger_ChatGPT_OpenAI\InstagramBot.py", line 31, in BotStart
    msginput = self.driver.find_element(By.XPATH, '/html/body/div[2]/div/div/div[1]/div/div/div/div[1]/div[1]/div/div[2]/div/section/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea') # Obtem o elemento responsavel por mandar mensagens
  File "C:\Users\shada\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\shada\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shada\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div/div/div[1]/div/div/div/div[1]/div[1]/div/div[2]/div/section/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea"}
  (Session info: chrome=111.0.5563.111)
Stacktrace:
Backtrace:
        (No symbol) [0x0059DCE3]
        (No symbol) [0x005339D1]
        (No symbol) [0x00444DA8]
        (No symbol) [0x0047019F]
        (No symbol) [0x004703AB]
        (No symbol) [0x0049EE62]
        (No symbol) [0x0048AF14]
        (No symbol) [0x0049D57C]
        (No symbol) [0x0048ACC6]
        (No symbol) [0x00466F68]
        (No symbol) [0x004680CD]
        GetHandleVerifier [0x00813832+2506274]
        GetHandleVerifier [0x00849794+2727300]
        GetHandleVerifier [0x0084E36C+2746716]
        GetHandleVerifier [0x00646690+617600]
        (No symbol) [0x0053C712]
        (No symbol) [0x00541FF8]
        (No symbol) [0x005420DB]
        (No symbol) [0x0054C63B]
        BaseThreadInitThunk [0x76437D59+25]
        RtlInitializeExceptionChain [0x7795B79B+107]
        RtlClearBits [0x7795B71F+191]
```

**Comment by JoseHenriqueSiqueira** [comment]
I'm working to resolve this. Instagram changed some classes and xpath, ended up breaking the code

**Comment by skshadan** [comment]
it is fix now?
