### ISSUE TITLE
Crashes after a while.What's going on ?

### ISSUE THREAD

**Issue by rexackermann** [JoseHenriqueSiqueira/WhatsaAppChatBot_OpenaiChatGPT_Python#6]
With this chrome appears :

`
python MessengerBot.py user.someone.00032 $OPENAI_API_KEY
`

Then I log in and after a while it crashes:

`
Traceback (most recent call last):
  File "/home/rex/github/Whatsapp_Instagram_Messanger_ChatGPT_OpenAI/MessengerBot.py", line 63, in <module>
    MessengerBot.BotStart()
  File "/home/rex/github/Whatsapp_Instagram_Messanger_ChatGPT_OpenAI/MessengerBot.py", line 30, in BotStart
    last_message = messages_element[-1].text if messages_element else ""
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 89, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/rex/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=114.0.5735.133)
Stacktrace:
#0 0x56417916d4e3 <unknown>
#1 0x564178e9cc76 <unknown>
#2 0x564178ea153c <unknown>
#3 0x564178ea297e <unknown>
#4 0x564178ea2a4c <unknown>
#5 0x564178ed3922 <unknown>
#6 0x564178ef8012 <unknown>
#7 0x564178eceb03 <unknown>
#8 0x564178ef81de <unknown>
#9 0x564178f1030e <unknown>
#10 0x564178ef7de3 <unknown>
#11 0x564178ecd2dd <unknown>
#12 0x564178ece34e <unknown>
#13 0x56417912d3e4 <unknown>
#14 0x5641791313d7 <unknown>
#15 0x56417913bb20 <unknown>
#16 0x564179132023 <unknown>
#17 0x5641791001aa <unknown>
#18 0x5641791566b8 <unknown>
#19 0x564179156847 <unknown>
#20 0x564179166243 <unknown>
#21 0x7f568de75907 start_thread
#22 0x7f568defb870 __clone3
`

**Comment by rexackermann** [comment]
It works now.I cloned the repo again and now it works.I will be closing the issue.Sorry for the inconvenience.
