### ISSUE TITLE
Can't Use

### ISSUE THREAD

**Issue by obhy** [JoseHenriqueSiqueira/WhatsaAppChatBot_OpenaiChatGPT_Python#7]
Show Error

`DevTools listening on ws://127.0.0.1:54887/devtools/browser/cb4d5c01-3552-481e-9908-ca3f3ebd1a14
[22628:24512:0717/114111.966:ERROR:device_event_log_impl.cc(222)] [11:41:11.966] USB: usb_service_win.cc:104 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
Traceback (most recent call last):
  File "C:\Users\2212\Documents\BOT\Whatsapp_Instagram_Messanger_ChatGPT_OpenAI\InstagramBot.py", line 60, in <module>
    InstBOT.BotStart()
  File "C:\Users\2212\Documents\BOT\Whatsapp_Instagram_Messanger_ChatGPT_OpenAI\InstagramBot.py", line 25, in BotStart
    msginput = self.driver.find_element(By.XPATH, '/html/body/div[2]/div/div/div[1]/div/div/div/div[1]/div[1]/div/div[2]/div/section/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea') # Obtem o elemento responsavel por mandar mensagens
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2212\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2212\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\2212\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div/div/div[1]/div/div/div/div[1]/div[1]/div/div[2]/div/section/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea"}
  (Session info: chrome=114.0.5735.199)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00E4A813+48355]
        (No symbol) [0x00DDC4B1]
        (No symbol) [0x00CE5358]
        (No symbol) [0x00D109A5]
        (No symbol) [0x00D10B3B]
        (No symbol) [0x00D3E232]
        (No symbol) [0x00D2A784]
        (No symbol) [0x00D3C922]
        (No symbol) [0x00D2A536]
        (No symbol) [0x00D082DC]
        (No symbol) [0x00D093DD]
        GetHandleVerifier [0x010AAABD+2539405]
        GetHandleVerifier [0x010EA78F+2800735]
        GetHandleVerifier [0x010E456C+2775612]
        GetHandleVerifier [0x00ED51E0+616112]
        (No symbol) [0x00DE5F8C]
        (No symbol) [0x00DE2328]
        (No symbol) [0x00DE240B]
        (No symbol) [0x00DD4FF7]
        BaseThreadInitThunk [0x768E7D59+25]
        RtlInitializeExceptionChain [0x7798B79B+107]
        RtlClearBits [0x7798B71F+191]

C:\Users\2212\Documents\BOT\Whatsapp_Instagram_Messanger_ChatGPT_OpenAI>`

**Comment by JoseHenriqueSiqueira** [comment]
Thanks. I will fix the bug today. Apparently selenium is not found the element by xpath.
